# This file was generated by GoReleaser. DO NOT EDIT.
class Qi < Formula
  desc ""
  homepage ""
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/razvvan/qi/releases/download/v0.0.1/qi_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "a37e4ce1118192d192302aa61c3a31884d95e5ac04472d601539442dba503e84"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/razvvan/qi/releases/download/v0.0.1/qi_0.0.1_Linux_x86_64.tar.gz"
      sha256 "4aaa626176908c344a4031ab1e302e86ccba6836158d05d3ab9b5f8ff529af2d"
    end
  end

  def install
    bin.install "qi"
  end
end
