# This file was generated by GoReleaser. DO NOT EDIT.
class Qi < Formula
  desc ""
  homepage ""
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/razvvan/qi/releases/download/v0.0.2/qi_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "aa8c397ede8112f5f618719357b31682582dfff700ec76a90c4d66536b97994c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/razvvan/qi/releases/download/v0.0.2/qi_0.0.2_Linux_x86_64.tar.gz"
      sha256 "5e5af8d15eb39a16b4795e3f43774a9e79739ee8a5a8c787c60973f3d8112abc"
    end
  end

  def install
    bin.install "qi"
  end
end
