# This file was generated by GoReleaser. DO NOT EDIT.
class Qi < Formula
  desc ""
  homepage ""
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/razvvan/qi/releases/download/v0.0.4/qi_0.0.4_Darwin_x86_64.tar.gz"
    sha256 "7e08060e9f9c814c69fbd3d5a52f5afc86c2b3b289f53dfe3aa957c410df209f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/razvvan/qi/releases/download/v0.0.4/qi_0.0.4_Linux_x86_64.tar.gz"
      sha256 "f87a47ef8422bdaf28d871a8cae59c5039b0def23a5539a150314f80abce5c1b"
    end
  end

  def install
    bin.install "qi"
  end
end
